# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 251251343c0215678bf3878ffd9605a2bdfd0cdd2b4b7930618a6e9ed507cc5735e30fe59a064be51f1efa1403a86a8de423eb5e8b7cd0cfe5c1424e4bd3f16e

test:
  secret_key_base: b2b1c1d955b2830a4b520df48790d51ed6d773cb5ecf28a97125c1a41ca61b736796d1c0c8b8e7e3c4a7eb56e976f8c0a805148274c52a45993a41d6d03acb9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
